const Documents = {
    'AAmap': require('../assets/pdf/AAmap.pdf'),
    'bazinga_menu':require('../assets/pdf/bazinga_menu.pdf'),
    'bus_time_table':require('../assets/pdf/bus_time_table.pdf'),
    'CAmap':require('../assets/pdf/CAmap.pdf'),
    'CCE_1':require('../assets/pdf/CCE_1.pdf'),
    'CCE_2':require('../assets/pdf/CCE_2.pdf'),
    'CCE_3':require('../assets/pdf/CCE_3.pdf'),
    'CCE_4':require('../assets/pdf/CCE_4.pdf'),
    'CSE_1':require('../assets/pdf/CSE_1.pdf'),
    'CSE_2':require('../assets/pdf/CSE_2.pdf'),
    'CSE_3':require('../assets/pdf/CSE_3.pdf'),
    'CSE_4':require('../assets/pdf/CSE_4.pdf'),
    'ECE_1':require('../assets/pdf/ECE_1.pdf'),
    'ECE_2':require('../assets/pdf/ECE_2.pdf'),
    'ECE_3':require('../assets/pdf/ECE_3.pdf'),
    'ECE_4':require('../assets/pdf/ECE_4.pdf'),
    'ME_1':require('../assets/pdf/ME_1.pdf'),
    'ME_2':require('../assets/pdf/ME_2.pdf'),
    'ME_3':require('../assets/pdf/ME_3.pdf'),
    'ME_4':require('../assets/pdf/ME_4.pdf'),
    'CSE':require('../assets/pdf/CSE.pdf'),
    'CCE':require('../assets/pdf/CCE.pdf'),
    'ECE':require('../assets/pdf/ECE.pdf'),
    'ME':require('../assets/pdf/ME.pdf'),
    'CounsellingProcess':require('../assets/pdf/CounsellingProcess.pdf'),
    'holiday_calendar':require('../assets/pdf/holiday_calendar.pdf'),
    'mess_menu':require('../assets/pdf/mess_menu.pdf'),
    'sop':require('../assets/pdf/sop.pdf'),
    'tfb_menu':require('../assets/pdf/tfb_menu.pdf'),
    'academic_calendar':require('../assets/pdf/academic_calendar.pdf'),
}

export default Documents;