const Images = {
    "gymkhana":{
        "cult":{
            "aaveg":require('../assets/cult/aaveg.png'),
            "capriccio":require('../assets/cult/capriccio.png'),
            "eminence":require('../assets/cult/eminence.png'),
            "imagination":require('../assets/cult/imagination.png'),
            "insignia":require('../assets/cult/insignia.png'),
            "literary_committee":require('../assets/cult/LC.png'),
            "media_cell":require('../assets/cult/media_cell.png'),
            "rendition":require('../assets/cult/rendition.png'),
            "sankalp":require('../assets/cult/sankalp.png'),
            "vignette":require('../assets/cult/vignette.png'),
            "fundoo":require('../assets/cult/fundoo.png')
        },
        "scitech":{
            "astro":require('../assets/scitech/astro.png'),
            "cipher":require('../assets/scitech/cipher.png'),
            "cybros":require('../assets/scitech/cybros.png'),
            "debsoc":require('../assets/scitech/debsoc.png'),
            "ecell":require('../assets/scitech/e_cell.png'),
            "phoenix":require('../assets/scitech/phoenix.png'),
            "quizzinga":require('../assets/scitech/quizzinga.png')
        },
        "sports":{
            "badminton":require('../assets/scitech/astro.png'),
            "basketball":require('../assets/scitech/cipher.png'),
            "chess":require('../assets/scitech/cybros.png'),
            "cricket":require('../assets/scitech/debsoc.png'),
            "football":require('../assets/scitech/e_cell.png'),
            "kabaddi":require('../assets/scitech/phoenix.png'),
            "table_tennis":require('../assets/scitech/quizzinga.png'),
            "volleyball":require('../assets/scitech/quizzinga.png'),
            "tennis":require('../assets/scitech/quizzinga.png'),
            "squash":require('../assets/scitech/quizzinga.png')
        },
        "fests":{
            "vivacity":require('../assets/cult/vivacity.png'),
            "plinth":require('../assets/scitech/plinth.png'),
            "desportivos":require('../assets/sports/despo.png')
        }
    }
}

export default Images;